### PR TITLE
REINITIATION OF PROJECT UNDER THE USE OF RUGBUST

### PR DESCRIPTION
**Pull request by 0xfadead**
## Notice
- [ ] I *understand* the code that I have edited, and have the means
to test it before making changes to Concord.

## What?

THIS COMMIT IMPLEMENTS PARTS OF THE CHANGES ANNOUNCED ON THE DISCORD SERVER.

## Why?

C IS DEPRECATED: AFTER THE RECENT XZ ATTACK WE HAVE DECIDED TO REWRITE THIS LIBRARY IN **MEMORY SAFE** RUST™ (NO AFFILIATION WITH THE RUST FUNDATION™!).
**ALL HAIL RUGBUST**

## How?

- DOCUMENTATION & EXAMPLES HAVE BEEN REMOVED, BECAUSE RUST IS SELF-DOCUMENTING
- TESTS HAVE BEEN REMOVED BECAUSE RUST IS PERFECT
- THE CONFIGURATION IS NOW HANDLED THROUGH TOML
- EVERYTHING HAS BEEN CHANGED TO RUST
- REMOVED BLOAT BY 98%, BY REMOVING UNNEEDED HEADERS

## Testing?

TESTED: 
UNTESTED: *

## Anything Else?

**ALL HAIL RUST**
**ALL HAIL RUST**

**ALL HAIL RUST**

**ALL HAIL RUST**

**ALL HAIL RUST**

**ALL HAIL RUST**

**This is a joke commit if this was somehow not obvious**

### CODE REVIEW

**Review by PancakeTAS — COMMENTED** [review]
LGTM

**Review by lcsmuller — CHANGES_REQUESTED** [review]
Not enough `unsafe` keyword usage

**Comment by Piecuuu** [comment]
Did you mention it's memory safe?

**Comment by 0xfadead** [comment]
> Not enough `unsafe` keyword usage

I WILL CERTAINLY FIX THIS ISSUE, AT THE SHORTEST AVAILABLE TIME.

**Comment by 0xfadead** [comment]
> Did you mention it's memory safe?

THIS WAS IMPLIED INSIDE THE `RUST IS PERFECT` POINT.
I DO, HOWEVER, APPRECIATE YOUR FEEDBACK.

**Comment by Piecuuu** [comment]
> > Did you mention it's memory safe?
> 
> THIS WAS IMPLIED INSIDE THE `TESTS HAVE BEEN REMOVED BECAUSE *RUST IS PERFECT*` POINT.
> I DO, HOWEVER, APPRECIATE YOUR FEEDBACK.

YOU HAVEN'T MENTIONED IT ENOUGH!! WE REQUIRE YOU TO DUNK ON C USERS EVEN MORE!!! THIS IS A DISGRACE TO THE RUST PROJECT!!! IN RUST WE TRUST! LONG LIVE RUST!!

**Comment by ThePedroo** [comment]
All of those affirmations above are non-sense and useless, we are more than aware that Rust is perfect and because of that, there's no need of specifying its benefits in a project, as it beats C in every way possible: Compability, performance, stability, security and etc.

While C developers are a minority and far from us humans, we still need to treat them like they were normal, so please don't use any bad word against them.

About the PR itself, it require multiple changes to follow the strict standards of the Rust (bad) good standards, used in numerous projects that were ported to Rust, one of them being the use of `unsafe` anywhere possible, but not limited to it, and expanded to others like use of dynamic memory everywhere and use of `clone` everywhere.

**Comment by jdeokkim** [comment]
I'm scared 😭

**Comment by oliveirarleo** [comment]
> as it beats C in every way possible: Compability, performance, stability, security and etc.

Forgot to mention that rust beats c in style points

**Comment by oliveirarleo** [comment]
I have noticed that some files were only renamed to `.rs`, so filthy to have unsafe/unholy code inside such a graceful file extension.

**Comment by 0xfadead** [comment]
> I have noticed that some files were only renamed to `.rs`, so filthy to have unsafe/unholy code inside such a graceful file extension.

I AM SO INCREDIBLY SORRY ABOUT THIS MISTAKE, I WILL BARADE CHATGPT® TO RE-GENERATE THE AFOREMENTIONED  CODE IN PERFECT RUST® AT THE SHORTEST AVAILABLE SPRINT.

WE AT COGMASTE.RS™ BELIEVE IN AGILE® AND ALL ITS BENEFITS, SO IT WOULD BE APPRECIATED IF YOU WERE SO KIND AS TO ASSIGN AN APPROPRIATE AMOUNT OF STORYPOINTS TO THIS ENDEAVOUR 😃

**Comment by lcsmuller** [comment]
I'm sorry

**Comment by 0xfadead** [comment]
> I'm sorry

MAY THE RUGBUST BE WITH YOU

**Pull request closed without merging**
