### PR TITLE
Fixed compiling error on Darwin

### PR DESCRIPTION
**Pull request by mrtuxa**
## What?
Fixed if not compiling error to if else

### CODE REVIEW

**Comment by tarbomb** [comment]
What exactly was the compiler error?

**Comment by HackerSmacker** [comment]
Hi, I think you are heavily mistaken. Your commit will result in OS X being identified as NeXTSTEP, which is clearly not the case (there are dedicated ifdefs for OS X). Also, you based your commits off of the master branch, which is out-of-date compared to the dev branch. You cannot invert the macro detections there, as, that mis-identifies the OS for the user agent string. Please note that OS X defines `__APPLE__` but not `__osf` or `__osf__`, as NeXTSTEP, being based on OSF's software, defines that macro. That macro there distinguishes between the two OSes.

**Comment by mrtuxa** [comment]
> What exactly was the compiler error?

```
% make -j12                                                    
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o cog-utils.o cog-utils.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o io_poller.o io_poller.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o user-agent.o user-agent.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o websockets.o websockets.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o curl-websocket.o curl-websocket.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o jsmn-find.o jsmn-find.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o json-build.o json-build.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o log.o log.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o logconf.o logconf.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o priority_queue.o priority_queue.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o anomap.o anomap.c
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o sha1.o sha1.c
websockets.c:516:5: warning: add explicit braces to avoid dangling else [-Wdangling-else]
    else
    ^
cc -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I. -I/usr/local/include    -c -o threadpool.o threadpool.c
1 warning generated.
cc -O2 -I. -Iapi -I../include -I../core gencodecs-pp.c -o gencodecs-pp
Generating forward definitions
Generating header
cc -E -O2 -I. -Iapi -I../include -I../core -DGENCODECS_INIT -DGENCODECS_JSON_ENCODER -DGENCODECS_JSON_DECODER -DGENCODECS_FORWARD -DGENCODECS_DATA -nostdinc -P discord_codecs.PRE.h | ./gencodecs-pp >> discord_codecs.c
cc -E -O2 -I. -Iapi -I../include -I../core -DGENCODECS_HEADER -DGENCODECS_DATA -nostdinc -P discord_codecs.PRE.h | ./gencodecs-pp >> discord_codecs.h
cc -E -O2 -I. -Iapi -I../include -I../core -DGENCODECS_INIT -DGENCODECS_JSON_ENCODER -DGENCODECS_JSON_DECODER -DGENCODECS_HEADER -nostdinc -P discord_codecs.PRE.h | ./gencodecs-pp >> discord_codecs.h
Generating source
cc -E -O2 -I. -Iapi -I../include -I../core -DGENCODECS_INIT -DGENCODECS_JSON_ENCODER -DGENCODECS_JSON_DECODER -DGENCODECS_DATA -nostdinc -P discord_codecs.PRE.h | ./gencodecs-pp >> discord_codecs.c
cc -c -O2 -I. -Iapi -I../include -I../core discord_codecs.c -o discord_codecs.o
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o concord-once.o concord-once.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-refcount.o discord-refcount.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-rest.o discord-rest.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-rest_request.o discord-rest_request.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-rest_ratelimit.o discord-rest_ratelimit.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-client.o discord-client.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-events.o discord-events.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-loop.o discord-loop.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-gateway.o discord-gateway.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-gateway_dispatch.o discord-gateway_dispatch.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-messagecommands.o discord-messagecommands.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-timer.o discord-timer.c
cc -c -O2 -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -std=c99 -pthread -D_XOPEN_SOURCE=600 -DLOG_USE_COLOR -I../include -I../core -I../gencodecs -I/usr/local/include -Wall -Wextra -Wshadow -Wdouble-promotion -Wconversion -Wpedantic -o discord-misc.o discord-misc.c
In file included from discord-gateway.c:8:
../include/osname.h:257:9: error: token is not a valid binary operator in a preprocessor subexpression
#if not defined __APPLE__
    ~~~ ^
1 error generated.
make[2]: *** [discord-gateway.o] Error 1
make[2]: *** Waiting for unfinished jobs....
discord-rest_request.c:510:25: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    __carray_init(dest, (size_t)src->size, struct discord_attachment, , );
    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../core/carray.h:77:26: note: expanded from macro '__carray_init'
    (carray)->realsize = length;                              \
                       ~ ^~~~~~
1 warning generated.
In file included from discord-rest_ratelimit.c:9:
../core/clock.h:284:18: warning: implicit conversion changes signedness: 'time_t' (aka 'long') to 'uint64_t' (aka 'unsigned long long') [-Wsign-conversion]
  res->seconds = time(NULL);
               ~ ^~~~~~~~~~
1 warning generated.
make[1]: *** [deps] Error 2
make: *** [static] Error 2

```

**Comment by HackerSmacker** [comment]
That's an ISO 646 issue, worked out in the dev branch. Also, your proposed change forces every OS to be NeXTSTEP.

**Comment by mrtuxa** [comment]
> so i need to use the dev branch?

**Comment by mrtuxa** [comment]
> Yes.
how can i clone it?

**Comment by HackerSmacker** [comment]
Just perform a checkout on the branch.

**Comment by HackerSmacker** [comment]
We do have a Discord as linked in the README, yes.

**Comment by mrtuxa** [comment]
> We do have a Discord as linked in the README, yes.

oh ok

**Pull request closed without merging**
